///-- Generated by 'setFitConditions' from the file 'fitConditions.txt' for constexpr initial values
#ifndef FITCONDITIONS_H
#define FITCONDITIONS_H
constexpr double amin = 0.000000e+00;
constexpr double amax = 1.000000e+00;
constexpr double da = 5.000000e-03;
constexpr double Hmin = 0.000000e+00;
constexpr double Hmax = 1.000000e+00;
constexpr double dH = 5.000000e-03;
constexpr unsigned int Na = 200;
constexpr unsigned int NH = 200;
constexpr unsigned int na = 7;
constexpr unsigned int nH = 7;
#endif ///-- FITCONDITIONS_H 
