/*
    Program for setting the fit conditions of GA.cpp
    generates the header file fitConditions.h
*/

#include <iostream>
#include <fstream>
#include <cmath>

int main(int argc, char *argv[])
{
    ///-- if no name has been passed use the name 'fitConditions.txt'
    const char *fname = argc > 1 ? argv[1] : "fitConditions.txt";
    std::ifstream fin(fname);
    if (!fin)
    {
        std::cout << "error! couldn't find file" << std::endl;
        return -1;
    }
    double amin, amax, da;
    double Hmin, Hmax, dH;
    ///-- the input file must contain 6 numbers with below order
    if (!(fin >> amin >> amax >> da >> Hmin >> Hmax >> dH))
    {
        std::cout << "error! there isn't enough values in file " << fname << std::endl;
        return -1;
    }
    fin.close();
    ///-- open the file 'fitConditions.h'
    std::ofstream fout("fitConditions.h");
    if (!fout)
    {
        std::cout << "error! opening file" << std::endl;
        return -1;
    }
    fout.setf(std::ios_base::scientific);
    fout << "///-- Generated by 'setFitConditions' from the file '"
         << fname << "' for constexpr initial values" << std::endl;
    fout << "#ifndef FITCONDITIONS_H\n";
    fout << "#define FITCONDITIONS_H\n";
    fout << "constexpr double amin = " << amin << ";" << std::endl;
    fout << "constexpr double amax = " << amax << ";" << std::endl;
    fout << "constexpr double da = " << da << ";" << std::endl;
    fout << "constexpr double Hmin = " << Hmin << ";" << std::endl;
    fout << "constexpr double Hmax = " << Hmax << ";" << std::endl;
    fout << "constexpr double dH = " << dH << ";" << std::endl;
    unsigned int Na = static_cast<unsigned int>((amax - amin) / da);
    unsigned int NH = static_cast<unsigned int>((Hmax - Hmin) / dH);
    unsigned int na = static_cast<unsigned int>(std::log(Na) / std::log(2));
    unsigned int nH = static_cast<unsigned int>(std::log(NH) / std::log(2));
    fout << "constexpr unsigned int Na = " << Na << ";" << std::endl;
    fout << "constexpr unsigned int NH = " << NH << ";" << std::endl;
    fout << "constexpr unsigned int na = " << na << ";" << std::endl;
    fout << "constexpr unsigned int nH = " << nH << ";" << std::endl;
    fout << "#endif ///-- FITCONDITIONS_H " << std::endl;
    fout.close();
    return 0;
}
